#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop
# and "Hi" on the newline on 9th time.

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then 
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
